CREATE TABLE IF NOT EXISTS public.job
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    price           DOUBLE PRECISION NOT NULL,
    job_provider_id BIGINT,
    category_id     BIGINT REFERENCES public.category (id)
);


