CREATE TABLE IF NOT EXISTS public.job_provider (
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(255) NOT NULL,
    image        VARCHAR(255),
    description  VARCHAR(255),
    phone_number VARCHAR(255),
    location_id  BIGINT,
    app_user_id  BIGINT,
    FOREIGN KEY (app_user_id) REFERENCES public.app_user(id)
    );
