CREATE TABLE IF NOT EXISTS public.location
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city           VARCHAR(255) NOT NULL,
    job_provider_id BIGINT REFERENCES public.job_provider (id) ON DELETE CASCADE,
    category_id     BIGINT REFERENCES public.category (id) ON DELETE CASCADE
);