spring:
  banner:
    location: classpath:/banner.txt

  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5438/e-majstor?ApplicationName=e-majstor'
    username: e-majstor
    password: e-majstor

  jpa:
    database: default
    open-in-view: false
    generate-ddl: false
    show-sql: false

    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_schema: public

  flyway:
    enabled: true
    create-schemas: public